'use strict';
const $=id=>document.getElementById(id);
const AVATARS=['🪐','👾','🐸','😎','🐈','🌻'];
const COLORS=['#c6fa64','#8bbcff','#d7a4ff','#ff97be','#ffc779'];
const EMOJI=['😀','😂','🥹','😍','😎','🥳','😭','😅','🥰','🤔','😴','🤯','🫡','😈','💀','👀','❤️','🧡','💛','💚','💙','💜','🔥','✨','🎉','👍','👎','🤝','🙌','✌️','🫶','💪','👾','🐸','🐈','🪐','🌻','🍕','☕','🎮','🚀','💯'];
const DEFAULT_STICKERS=[{id:'frog',name:'Żabka',emoji:'🐸'},{id:'party',name:'Impreza',emoji:'🥳'},{id:'love',name:'Miłość',emoji:'🥰'},{id:'alien',name:'Kosmita',emoji:'👾'},{id:'fire',name:'Ogień',emoji:'🔥'},{id:'cat',name:'Kot',emoji:'🐈'}];
let stickers=[...DEFAULT_STICKERS];
let profile={nick:'',color:COLORS[0],avatar:AVATARS[0]};
let peer=null,hostConnection=null,isHost=false,room='',selfId='',active=false,busy=false,session=0;
let people=new Map(),connections=new Map(),history=[],typing=new Map(),lastTyping=0,lastSent=0;
let joinTimer,toastTimer,stopTypingTimer,pickerMode='emoji',connectReject;
function element(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e}
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200)}
function storageGet(key){try{return localStorage.getItem(key)}catch{return null}}
// Preserve the chosen hue while keeping nicknames readable in either theme.
function readableColor(hex){let rgb=hex.slice(1).match(/../g).map(n=>parseInt(n,16));const light=document.documentElement.dataset.theme==='light';const luminance=c=>c.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);const bg=light?.98:.012;for(let i=0;i<25;i++){const l=luminance(rgb);if((Math.max(l,bg)+.05)/(Math.min(l,bg)+.05)>=4.5)break;rgb=rgb.map(v=>Math.round(light?v*.86:v+(255-v)*.14))}return '#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join('')}
function paintNickColors(){document.querySelectorAll('[data-nick-color]').forEach(e=>e.style.color=readableColor(e.dataset.nickColor))}
function saveProfile(){try{localStorage.setItem('pokoj-profile',JSON.stringify(profile))}catch{notify('Profil działa, ale przeglądarka nie pozwala go zapamiętać.')}}
function validProfile(p){return !!p&&typeof p.nick==='string'&&p.nick.trim().length>0&&p.nick.length<=24&&/^#[0-9a-f]{6}$/i.test(p.color)&&typeof p.avatar==='string'&&(AVATARS.includes(p.avatar)||(/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(p.avatar)&&p.avatar.length<65000))}
try{const saved=JSON.parse(storageGet('pokoj-profile'));if(validProfile(saved))profile=saved}catch{}
$('nick').value=profile.nick;$('color').value=profile.color;
function avatarNode(value,large=false){const e=element('div','avatar'+(large?' large':''));if(value.startsWith('data:image/')){const img=element('img');img.src=value;img.alt='';e.append(img)}else e.textContent=value;return e}
function paintProfile(){const a=avatarNode(profile.avatar,true);a.id='avatar-preview';$('avatar-preview').replaceWith(a);$('nick-preview').textContent=profile.nick||'Twój nick';$('nick-preview').dataset.nickColor=profile.color;$('nick-preview').style.color=readableColor(profile.color);document.querySelectorAll('.avatar-choice').forEach(b=>{b.classList.toggle('selected',b.textContent===profile.avatar);b.setAttribute('aria-pressed',String(b.textContent===profile.avatar))});document.querySelectorAll('.swatch').forEach(b=>{b.classList.toggle('selected',b.dataset.color===profile.color);b.setAttribute('aria-pressed',String(b.dataset.color===profile.color))})}
for(const value of AVATARS){const b=element('button','avatar-choice',value);b.setAttribute('aria-label','Awatar '+value);b.onclick=()=>{profile.avatar=value;paintProfile();saveProfile()};$('avatars').append(b)}
for(const value of COLORS){const b=element('button','swatch');b.style.background=value;b.dataset.color=value;b.setAttribute('aria-label','Kolor '+value);b.onclick=()=>{profile.color=value;$('color').value=value;paintProfile();saveProfile()};$('colors').append(b)}
$('nick').oninput=()=>{profile.nick=$('nick').value.trim();paintProfile();saveProfile()};$('color').oninput=()=>{profile.color=$('color').value;paintProfile();saveProfile()};paintProfile();
function setTheme(theme){document.documentElement.dataset.theme=theme;paintNickColors();$('theme').textContent=theme==='dark'?'☀':'☾';$('theme').setAttribute('aria-label',theme==='dark'?'Włącz jasny motyw':'Włącz czarny motyw');try{localStorage.setItem('pokoj-theme',theme)}catch{}}
setTheme(storageGet('pokoj-theme')==='light'?'light':'dark');$('theme').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
$('upload').onchange=async()=>{const file=$('upload').files[0];if(!file)return;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024)throw Error('Wybierz JPG, PNG lub WEBP do 8 MB.');const url=URL.createObjectURL(file);const img=new Image();try{img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const size=Math.min(img.width,img.height);canvas.getContext('2d').drawImage(img,(img.width-size)/2,(img.height-size)/2,size,size,0,0,128,128);profile.avatar=canvas.toDataURL('image/jpeg',.8);paintProfile();saveProfile()}finally{URL.revokeObjectURL(url)}}catch(e){notify(e.message||'Nie udało się odczytać zdjęcia.')}finally{$('upload').value=''}};
fetch('stickers/manifest.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(items=>{if(!Array.isArray(items))throw Error();stickers.push(...items.filter(s=>s&&typeof s.id==='string'&&/^[a-z0-9_-]{1,40}$/i.test(s.id)&&!DEFAULT_STICKERS.some(d=>d.id===s.id)&&typeof s.name==='string'&&s.name.length<=60&&typeof s.file==='string'&&/^[a-z0-9_-]+\.(png|webp|gif|jpe?g)$/i.test(s.file)).slice(0,80));if(pickerMode==='sticker')renderPicker()}).catch(()=>notify('Nie udało się wczytać własnych naklejek. Dostępne są naklejki startowe.'));
function roomCode(input){let value=input.trim();if(value.includes('://')){try{value=new URL(value).hash.replace('#','')}catch{return ''}}return value.replace(/[\s-]/g,'').toUpperCase()}
function randomCode(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from(crypto.getRandomValues(new Uint8Array(12)),n=>alphabet[n%32]).join('')}
function formatCode(code){return code.match(/.{1,4}/g)?.join('-')||code}
const initialCode=roomCode(location.hash.slice(1));if(/^[A-HJ-NP-Z2-9]{12}$/.test(initialCode))$('room-code').value=formatCode(initialCode);
function status(text,error=false){$('connection-status').textContent=text;$('connection-status').classList.toggle('error',error)}
function setBusy(value){busy=value;$('create').disabled=value;$('join').disabled=value;$('nick').disabled=value;$('color').disabled=value;document.querySelectorAll('.avatar-choice,.swatch').forEach(b=>b.disabled=value);$('upload').disabled=value}
function sendTo(connection,data){if(!connection?.open)return false;try{connection.send(data);return true}catch{return false}}
function broadcast(data){for(const c of connections.values())sendTo(c,data)}
function roster(){const data={type:'roster',people:[...people.values()]};broadcast(data);renderPeople()}
function renderPeople(){$('people').replaceChildren();$('people-count').textContent=people.size;for(const p of people.values()){const row=element('div','person');row.append(avatarNode(p.avatar));const info=element('div'),name=element('div','person-name',p.nick+(p.id===selfId?' (Ty)':''));name.dataset.nickColor=p.color;name.style.color=readableColor(p.color);info.append(name,element('small','',p.host?'Twórca pokoju':'W pokoju'));row.append(info);$('people').append(row)}}
function enterChat(){active=true;setBusy(false);clearTimeout(joinTimer);$('lobby').hidden=true;$('chat').hidden=false;$('code-label').textContent=formatCode(room);$('host-note').textContent=isHost?'Jesteś gospodarzem. Zostaw tę kartę otwartą, żeby pokój działał.':'Pokój działa, dopóki gospodarz jest online. Wiadomości nie są zapisywane na serwerze.';$('chat-status').textContent='Połączono';$('message').disabled=false;$('send').disabled=false;$('picker-toggle').disabled=false;window.history.replaceState(null,'','#'+room);renderPeople();$('message').focus()}
function resetSession(){session++;clearTimeout(joinTimer);clearTimeout(stopTypingTimer);connectReject=null;active=false;busy=false;const oldPeer=peer;peer=null;hostConnection=null;connections.clear();people.clear();history=[];typing.clear();room='';selfId='';isHost=false;oldPeer?.destroy();$('messages').querySelectorAll('.message-row').forEach(e=>e.remove());$('empty-chat').hidden=false;$('typing').replaceChildren();$('message').value='';$('message').style.height='';setPicker(false);$('chat').hidden=true;$('lobby').hidden=false;setBusy(false)}
function closeRoom(text){if(!active)return;active=false;typing.clear();$('typing').replaceChildren();$('chat-status').textContent='Rozłączono';$('message').disabled=true;$('send').disabled=true;$('picker-toggle').disabled=true;setPicker(false);notify(text);$('host-note').textContent=text;peer?.destroy();connections.clear()}
const errorText=err=>({'peer-unavailable':'Nie znaleziono pokoju. Sprawdź kod i czy gospodarz jest online.','unavailable-id':'Ten kod jest zajęty. Spróbuj utworzyć pokój jeszcze raz.','network':'Nie udało się połączyć. Sprawdź internet i spróbuj ponownie.','browser-incompatible':'Ta przeglądarka nie obsługuje czatu. Użyj aktualnego Chrome, Edge, Firefox lub Safari.','room-full':'Pokój jest pełny (maksymalnie 12 osób).'}[err?.type]||err?.message||'Połączenie nie powiodło się. Spróbuj ponownie.');
async function connectRoom(host,code){if(busy||active)return;if(!validProfile(profile)){$('nick').focus();status('Najpierw wpisz swój nick.',true);return}if(!host&&!/^[A-HJ-NP-Z2-9]{12}$/.test(code)){status('Wpisz pełny kod pokoju (12 znaków) lub link zaproszenia.',true);return}if(typeof Peer==='undefined'){status('Nie wczytano biblioteki czatu. Odśwież stronę.',true);return}resetSession();isHost=host;room=host?randomCode():code;setBusy(true);status(host?'Otwieram Twój pokój…':'Łączę z pokojem…');saveProfile();const currentSession=session;
  try{await new Promise((resolve,reject)=>{connectReject=reject;let ready=false;peer=new Peer(host?'pokoj-v1-'+room:undefined,{debug:0});joinTimer=setTimeout(()=>reject(Error('Pokój nie odpowiada. Sprawdź kod, internet i czy gospodarz ma otwartą kartę. Niektóre sieci blokują połączenia bezpośrednie.')),20000);
    peer.on('error',err=>{if(currentSession!==session)return;if(!ready)reject(Error(errorText(err)));else notify(errorText(err))});
    peer.on('disconnected',()=>{if(currentSession!==session||!active)return;$('chat-status').textContent='Ponowne łączenie…';try{peer.reconnect()}catch{notify('Utracono połączenie z usługą zaproszeń.')}});
    peer.on('open',id=>{if(currentSession!==session)return;if(ready){$('chat-status').textContent='Połączono';return}selfId=id;if(host){people.set(id,{...profile,id,host:true});ready=true;enterChat();resolve()}else{hostConnection=peer.connect('pokoj-v1-'+room,{reliable:true,serialization:'json'});const c=hostConnection;c.on('open',()=>sendTo(c,{type:'hello',profile}));c.on('data',data=>{if(currentSession!==session)return;if(data?.type==='rejected'){if(!ready)reject(Error(data.reason==='full'?errorText({type:'room-full'}):'Pokój odrzucił połączenie.'));return}if(!ready){if(data?.type!=='welcome'||!validRoster(data.people)||!data.people.some(p=>p.id===selfId)||!Array.isArray(data.messages))return;people=new Map(data.people.map(p=>[p.id,p]));ready=true;enterChat();for(const msg of data.messages.slice(-100))if(validMessage(msg))appendMessage(msg);receiveExtraWelcome(data);resolve()}else receiveFromHost(data)});c.on('close',()=>{if(currentSession!==session)return;if(!ready)reject(Error('Pokój został zamknięty.'));else closeRoom('Gospodarz opuścił pokój lub utracił połączenie. Utwórz nowy pokój, żeby rozmawiać dalej.')});c.on('error',()=>{if(currentSession!==session)return;if(!ready)reject(Error('Nie udało się dołączyć do pokoju.'));else closeRoom('Połączenie z gospodarzem zostało przerwane.')})}});
    peer.on('connection',c=>{if(currentSession!==session||!isHost){c.on('open',()=>c.close());return}acceptGuest(c,currentSession)});
  });connectReject=null;status('Pokój gotowy.')}catch(err){if(currentSession!==session)return;resetSession();status(errorText(err),true)}
}
function acceptGuest(c,currentSession){let joined=false,lastMessage=0,lastType=0;const timeout=setTimeout(()=>{if(!joined)c.close()},10000);c.on('error',()=>{});c.on('data',data=>{if(currentSession!==session||!active||!data||typeof data!=='object')return;
  if(!joined){if(data.type!=='hello'||!validProfile(data.profile)){c.close();return}if(people.size>=12||connections.size>=11){sendTo(c,{type:'rejected',reason:'full'});setTimeout(()=>c.close(),200);return}if(people.has(c.peer)){c.close();return}joined=true;clearTimeout(timeout);people.set(c.peer,{nick:data.profile.nick.trim(),color:data.profile.color,avatar:data.profile.avatar,id:c.peer,host:false});connections.set(c.peer,c);sendTo(c,{type:'welcome',people:[...people.values()],messages:history.slice(-100),extras:extraSnapshot()});sendExtraHistory(c);roster();return}
  if(data.type==='message'){if(Date.now()-lastMessage<350)return;lastMessage=Date.now();publishMessage(c.peer,data)}else if(data.type==='typing'&&typeof data.value==='boolean'){if(data.value&&Date.now()-lastType<500)return;lastType=Date.now();publishTyping(c.peer,data.value)}else if(['asset-chunk','read','reaction'].includes(data.type))extraAccept(c.peer,data)
});c.on('close',()=>{clearTimeout(timeout);if(currentSession!==session||!joined)return;connections.delete(c.peer);people.delete(c.peer);typing.delete(c.peer);roster();renderTyping()})}
function validRoster(list){return Array.isArray(list)&&list.length<=12&&list.every(p=>validProfile(p)&&typeof p.id==='string'&&p.id.length<=100&&typeof p.host==='boolean')}
function validMessage(m){return !!m&&typeof m.id==='string'&&m.id.length<100&&validProfile(m.author)&&typeof m.author.id==='string'&&Number.isFinite(m.time)&&((m.kind==='text'&&typeof m.text==='string'&&m.text.length>0&&m.text.length<=2000)||(m.kind==='sticker'&&stickers.some(s=>s.id===m.sticker))||validExtraMessage(m))}
function publishMessage(id,data){const author=people.get(id);if(!author)return;const m={id:crypto.randomUUID(),time:Date.now(),author:{...author},kind:data.kind};if(data.kind==='text'&&typeof data.text==='string')m.text=data.text.trim();else if(data.kind==='sticker')m.sticker=data.sticker;else if(data.kind==='code'){m.text=data.text;m.language=data.language}else if(data.kind==='asset')m.asset=data.asset;if(!validMessage(m))return;if(m.kind==='asset'&&!extraAssetReady(id,m.asset.id))return;history.push(m);if(history.length>100)history.shift();appendMessage(m);broadcast({type:'message',message:m});publishTyping(id,false)}
function receiveFromHost(data){if(!active||!data)return;if(data.type==='message'&&validMessage(data.message))appendMessage(data.message);if(data.type==='roster'&&validRoster(data.people)){people=new Map(data.people.map(p=>[p.id,p]));renderPeople();for(const id of typing.keys())if(!people.has(id))typing.delete(id);renderTyping()}if(data.type==='typing'&&typeof data.id==='string'&&typeof data.value==='boolean'&&people.has(data.id)){if(data.value)typing.set(data.id,Date.now());else typing.delete(data.id);renderTyping()}if(data.type==='closed')closeRoom('Gospodarz zamknął pokój. Możesz stworzyć kolejny.');if(['asset-chunk','read','reaction'].includes(data.type))extraReceive(data)}
function appendMessage(m){if([...$('messages').children].some(e=>e.dataset.id===m.id))return;const nearBottom=$('messages').scrollHeight-$('messages').scrollTop-$('messages').clientHeight<130;$('empty-chat').hidden=true;const row=element('article','message-row');row.dataset.id=m.id;row.append(avatarNode(m.author.avatar));const body=element('div','message-body'),meta=element('div','message-meta'),name=element('strong','',m.author.nick);name.dataset.nickColor=m.author.color;name.style.color=readableColor(m.author.color);const time=element('time','',new Date(m.time).toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'}));time.dateTime=new Date(m.time).toISOString();meta.append(name,time);body.append(meta);if(m.kind==='text')body.append(element('div','message-content',m.text));else if(m.kind==='code'||m.kind==='asset'){renderExtraContent(body,m)}else{const s=stickers.find(s=>s.id===m.sticker);if(!s)return;if(s.emoji){const e=element('div','message-content sticker-emoji',s.emoji);e.setAttribute('aria-label',s.name);body.append(e)}else{const img=element('img','message-content sticker-image');img.src='stickers/'+s.file;img.alt=s.name;img.onload=()=>{if(nearBottom)$('messages').scrollTop=$('messages').scrollHeight};body.append(img)}}row.append(body);decorateMessage(row,m);$('messages').append(row);while($('messages').querySelectorAll('.message-row').length>200)$('messages').querySelector('.message-row').remove();if(nearBottom||m.author.id===selfId)$('messages').scrollTop=$('messages').scrollHeight;typing.delete(m.author.id);renderTyping()}
function publishTyping(id,value){if(value)typing.set(id,Date.now());else typing.delete(id);broadcast({type:'typing',id,value});renderTyping()}
function emitTyping(value){if(!active)return;if(value&&Date.now()-lastTyping<900)return;lastTyping=Date.now();if(isHost)publishTyping(selfId,value);else sendTo(hostConnection,{type:'typing',value})}
function renderTyping(){const names=[...typing].filter(([id,t])=>id!==selfId&&Date.now()-t<3500&&people.has(id)).map(([id])=>people.get(id).nick);$('typing').replaceChildren();if(!names.length)return;const dots=element('span','typing-dots');dots.append(element('i'),element('i'),element('i'));$('typing').append(dots,document.createTextNode(names.slice(0,3).join(', ')+(names.length>3?' i inni':'')+(names.length===1?' pisze…':' piszą…')))}
setInterval(renderTyping,1000);
function sendMessage(kind,textOrSticker){if(!active)return false;if(Date.now()-lastSent<400){notify('Chwileczkę — wysyłasz bardzo szybko.');return false}const data={type:'message',kind,...(kind==='text'?{text:textOrSticker.trim()}:{sticker:textOrSticker})};if(kind==='text'&&!data.text)return false;lastSent=Date.now();if(isHost)publishMessage(selfId,data);else if(!sendTo(hostConnection,data)){notify('Brak połączenia. Wiadomość nie została wysłana.');return false}emitTyping(false);return true}
$('create').onclick=()=>connectRoom(true,'');$('join-form').onsubmit=e=>{e.preventDefault();connectRoom(false,roomCode($('room-code').value))};
$('message-form').onsubmit=e=>{e.preventDefault();if(sendMessage('text',$('message').value)){$('message').value='';$('message').style.height='';setPicker(false);$('message').focus()}};
$('message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('message-form').requestSubmit()}};
$('message').oninput=()=>{emitTyping(!!$('message').value.trim());clearTimeout(stopTypingTimer);stopTypingTimer=setTimeout(()=>emitTyping(false),2200);$('message').style.height='auto';$('message').style.height=Math.min($('message').scrollHeight,120)+'px'};
$('message').onblur=()=>emitTyping(false);
function setPicker(open){$('picker').hidden=!open;$('picker-toggle').setAttribute('aria-expanded',String(open));if(open)renderPicker()}
function renderPicker(){$('emoji-tab').setAttribute('aria-pressed',String(pickerMode==='emoji'));$('sticker-tab').setAttribute('aria-pressed',String(pickerMode==='sticker'));$('picker-items').classList.toggle('stickers',pickerMode==='sticker');$('picker-items').replaceChildren();if(pickerMode==='emoji'){for(const emoji of EMOJI){const b=element('button','',emoji);b.setAttribute('aria-label','Wstaw '+emoji);b.onclick=()=>{const input=$('message');if(input.value.length+emoji.length>2000)return;input.setRangeText(emoji,input.selectionStart,input.selectionEnd,'end');input.dispatchEvent(new Event('input'));input.focus()};$('picker-items').append(b)}}else for(const s of stickers){const b=element('button');b.setAttribute('aria-label','Wyślij naklejkę: '+s.name);if(s.emoji)b.textContent=s.emoji;else{const img=element('img');img.src='stickers/'+s.file;img.alt=s.name;b.append(img)}b.onclick=()=>{if(sendMessage('sticker',s.id)){setPicker(false);$('message').focus()}};$('picker-items').append(b)}}
$('picker-toggle').onclick=()=>setPicker($('picker').hidden);$('close-picker').onclick=()=>{setPicker(false);$('picker-toggle').focus()};$('emoji-tab').onclick=()=>{pickerMode='emoji';renderPicker()};$('sticker-tab').onclick=()=>{pickerMode='sticker';renderPicker()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('picker').hidden){setPicker(false);$('picker-toggle').focus()}});document.addEventListener('click',e=>{if(!$('picker').contains(e.target)&&!$('picker-toggle').contains(e.target))setPicker(false)});
$('invite').onclick=async()=>{const url=new URL(location.href);url.hash=room;try{await navigator.clipboard.writeText(url.href);notify('Link skopiowany. Podeślij go znajomym!')}catch{notify('Nie udało się skopiować. Skopiuj link z paska adresu.')}};
$('leave').onclick=()=>{$('leave-description').textContent=isHost&&active?'Jesteś gospodarzem. Wyjście zamknie pokój wszystkim uczestnikom.':'Po wyjściu historia rozmowy zniknie z tego widoku.';$('leave-dialog').showModal()};$('cancel-leave').onclick=()=>$('leave-dialog').close();$('confirm-leave').onclick=()=>{if(isHost&&active)broadcast({type:'closed'});$('leave-dialog').close();resetSession();window.history.replaceState(null,'',location.pathname+location.search);status('Możesz stworzyć nowy pokój lub dołączyć do znajomych.');$('create').focus()};
window.addEventListener('beforeunload',e=>{if(active){e.preventDefault();e.returnValue=''}});window.addEventListener('pagehide',()=>peer?.destroy());
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'prepare_room_join',title:'Przygotuj dołączenie do pokoju',description:'Wpisuje kod pokoju w formularzu. Nie nawiązuje połączenia i nie wysyła wiadomości.',inputSchema:{type:'object',properties:{code:{type:'string'}},required:['code'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(active||busy)throw Error('Najpierw wyjdź z aktualnego pokoju.');const code=roomCode(typeof input?.code==='string'?input.code:'');if(!/^[A-HJ-NP-Z2-9]{12}$/.test(code))throw Error('Nieprawidłowy kod pokoju.');$('room-code').value=formatCode(code);$('room-code').focus();return {code:formatCode(code),status:'prepared'}}})).catch(()=>{})}catch{}}
