'use strict';
// Room-only extras. The host validates and relays state to every participant.
const extraMessages=new Map(),extraAssets=new Map(),extraReads=new Map(),extraReactions=new Map();
const EXTRA_MAX=3*1024*1024, EXTRA_CHUNK=12000, EXTRA_EMOJI=['❤️','😂','👍','🔥','😮','😭'];
let savedStickers=[],stickerDatabase;

function validExtraMessage(m){
  if(m.kind==='code')return typeof m.text==='string'&&m.text.length>0&&m.text.length<=20000&&['HTML','CSS','JavaScript','JSON','Python','Inny'].includes(m.language);
  if(m.kind==='asset')return !!m.asset&&typeof m.asset.id==='string'&&/^[a-f0-9-]{36}$/.test(m.asset.id)&&typeof m.asset.name==='string'&&m.asset.name.length<=120&&typeof m.asset.mime==='string'&&m.asset.mime.length<=80&&Number.isInteger(m.asset.size)&&m.asset.size>0&&m.asset.size<=EXTRA_MAX&&typeof m.asset.sticker==='boolean';
  return false;
}
function extraAssetReady(owner,id){const asset=extraAssets.get(id);return !!asset&&asset.owner===owner&&asset.complete}
function roomMessage(id){return history.find(m=>m.id===id)}
function extraSnapshot(){return {reads:[...extraReads].map(([id,users])=>[id,[...users]]),reactions:[...extraReactions].map(([id,emojiMap])=>[id,[...emojiMap].map(([emoji,users])=>[emoji,[...users]])])}}
function receiveExtraWelcome(data){const state=data.extras;if(!state||typeof state!=='object')return;for(const [id,users] of (Array.isArray(state.reads)?state.reads:[])){if(typeof id==='string'&&Array.isArray(users))extraReads.set(id,new Set(users.filter(u=>typeof u==='string')))}for(const [id,reactions] of (Array.isArray(state.reactions)?state.reactions:[])){if(typeof id==='string'&&Array.isArray(reactions))extraReactions.set(id,new Map(reactions.filter(r=>Array.isArray(r)&&EXTRA_EMOJI.includes(r[0])&&Array.isArray(r[1])).map(([emoji,users])=>[emoji,new Set(users.filter(u=>typeof u==='string'))])))}document.querySelectorAll('.message-row').forEach(row=>paintExtraState(row.dataset.id))}
function sendExtraHistory(connection){const sent=new Set();for(const m of history){if(m.kind!=='asset'||sent.has(m.asset.id))continue;sent.add(m.asset.id);const asset=extraAssets.get(m.asset.id);if(asset?.complete)for(let i=0;i<asset.chunks.length;i++)sendTo(connection,{type:'asset-chunk',owner:asset.owner,id:m.asset.id,index:i,total:asset.chunks.length,name:asset.name,mime:asset.mime,size:asset.size,sticker:asset.sticker,data:asset.chunks[i]})}}

function receiveExtraChunk(data,owner){
  if(!data||typeof data.id!=='string'||!/^[a-f0-9-]{36}$/.test(data.id)||!Number.isInteger(data.index)||!Number.isInteger(data.total)||data.total<1||data.total>350||data.index<0||data.index>=data.total||typeof data.data!=='string'||data.data.length>17000||!/^[A-Za-z0-9+/]*={0,2}$/.test(data.data)||typeof data.name!=='string'||data.name.length>120||typeof data.mime!=='string'||data.mime.length>80||!Number.isInteger(data.size)||data.size<1||data.size>EXTRA_MAX||typeof data.sticker!=='boolean')return false;
  if(data.sticker&&!/^image\/(png|jpeg|webp|gif)$/.test(data.mime))return false;
  let asset=extraAssets.get(data.id);
  if(!asset){asset={owner,name:data.name,mime:data.mime,size:data.size,sticker:data.sticker,chunks:Array(data.total),count:0,complete:false};extraAssets.set(data.id,asset)}
  if(asset.owner!==owner||asset.chunks.length!==data.total||asset.name!==data.name||asset.size!==data.size||asset.mime!==data.mime||asset.sticker!==data.sticker)return false;
  if(!asset.chunks[data.index]){asset.chunks[data.index]=data.data;asset.count++}
  if(asset.count===asset.chunks.length&&!asset.complete){try{const raw=atob(asset.chunks.join(''));if(raw.length!==asset.size)throw Error();const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));asset.url=URL.createObjectURL(new Blob([bytes],{type:asset.mime}));asset.complete=true;document.querySelectorAll('.message-row').forEach(row=>{const msg=extraMessages.get(row.dataset.id);if(msg?.asset?.id===data.id){const body=row.querySelector('.message-body');const old=body.querySelector('.asset-content');if(old)old.replaceWith(makeAssetContent(msg))}})}catch{extraAssets.delete(data.id);return false}}
  return true;
}
function extraAccept(peerId,data){
  if(data.type==='asset-chunk'){if(receiveExtraChunk(data,peerId))broadcast({...data,owner:peerId});return}
  const message=roomMessage(data.id);if(!message||!people.has(peerId)||typeof data.id!=='string')return;
  if(data.type==='read'){if(peerId===message.author.id)return;let users=extraReads.get(data.id);if(!users){users=new Set();extraReads.set(data.id,users)}users.add(peerId);extraReceive({type:'read',id:data.id,users:[...users]});broadcast({type:'read',id:data.id,users:[...users]})}
  if(data.type==='reaction'&&EXTRA_EMOJI.includes(data.emoji)){let map=extraReactions.get(data.id);if(!map){map=new Map();extraReactions.set(data.id,map)}let users=map.get(data.emoji);if(!users){users=new Set();map.set(data.emoji,users)}if(users.has(peerId))users.delete(peerId);else users.add(peerId);const packet={type:'reaction',id:data.id,emoji:data.emoji,users:[...users]};extraReceive(packet);broadcast(packet)}
}
function extraReceive(data){
  if(data.type==='asset-chunk'){if(people.has(data.owner))receiveExtraChunk(data,data.owner);return}
  if(typeof data.id!=='string'||!extraMessages.has(data.id)||!Array.isArray(data.users)||data.users.length>12||!data.users.every(u=>typeof u==='string'&&u.length<=100))return;
  if(data.type==='read')extraReads.set(data.id,new Set(data.users));
  if(data.type==='reaction'&&EXTRA_EMOJI.includes(data.emoji)){let map=extraReactions.get(data.id);if(!map){map=new Map();extraReactions.set(data.id,map)}map.set(data.emoji,new Set(data.users))}
  paintExtraState(data.id)
}
function emitExtra(data){if(!active)return;if(isHost)extraAccept(selfId,data);else sendTo(hostConnection,data)}
function reportRead(id){if(!active||document.hidden||!document.hasFocus())return;const message=extraMessages.get(id);if(!message||message.author.id===selfId||extraReads.get(id)?.has(selfId))return;emitExtra({type:'read',id})}
const readObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)reportRead(entry.target.dataset.id)},{root:$('messages'),threshold:.35});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)document.querySelectorAll('.message-row').forEach(row=>reportRead(row.dataset.id))});
window.addEventListener('focus',()=>document.querySelectorAll('.message-row').forEach(row=>reportRead(row.dataset.id)));

function makeAssetContent(m){const asset=extraAssets.get(m.asset.id),wrap=element('div','asset-content');if(!asset?.complete){wrap.textContent='📎 '+m.asset.name+' · Plik jest przesyłany lub nie jest już dostępny.';return wrap}const safeImage=/^image\/(jpeg|png|gif|webp)$/.test(asset.mime);if(safeImage){const img=element('img',m.asset.sticker?'sticker-image':'shared-image');img.src=asset.url;img.alt=m.asset.name;img.loading='lazy';const link=element('a','asset-image-link');link.href=asset.url;link.target='_blank';link.rel='noopener';link.append(img);wrap.append(link)}if(!m.asset.sticker){const link=element('a','file-download','↓ '+m.asset.name+' · '+formatSize(m.asset.size));link.href=asset.url;link.download=m.asset.name;wrap.append(link)}return wrap}
function formatSize(n){return n<1024?`${n} B`:n<1048576?`${Math.ceil(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`}
function renderExtraContent(body,m){if(m.kind==='asset'){body.append(makeAssetContent(m));return}const panel=element('div','code-panel'),head=element('div','code-head'),lang=element('span','',m.language),copy=element('button','tiny-button','Kopiuj kod'),download=element('button','tiny-button','Pobierz');copy.type=download.type='button';copy.onclick=()=>copyText(m.text);download.onclick=()=>downloadCode(m);head.append(lang,copy,download);const pre=element('pre','code-pre');pre.tabIndex=0;const lines=m.text.split('\n');for(let i=0;i<lines.length;i++){const row=element('div','code-line'),number=element('span','code-number',String(i+1)),code=element('span','code-text');highlightCode(code,lines[i],m.language);row.append(number,code);pre.append(row)}panel.append(head,pre);body.append(panel)}
function highlightCode(container,line,language){const pattern=/(\/\/.*$|<!--.*?-->|#[^\n]*$|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\b(?:const|let|var|function|return|if|else|for|while|class|import|export|async|await|def|print|true|false|null|None)\b|<\/?[A-Za-z][\w-]*|\b\d+(?:\.\d+)?\b)/g;let pos=0;for(const match of line.matchAll(pattern)){if(match.index>pos)container.append(document.createTextNode(line.slice(pos,match.index)));const value=match[0];const kind=/^(\/\/|<!--|#)/.test(value)&&language!=='CSS'?'comment':/^["']/.test(value)?'string':/^\d/.test(value)?'number':'keyword';container.append(element('span','syntax-'+kind,value));pos=match.index+value.length}container.append(document.createTextNode(line.slice(pos)))}
function downloadCode(m){const extension={HTML:'html',CSS:'css',JavaScript:'js',JSON:'json',Python:'py',Inny:'txt'}[m.language];const url=URL.createObjectURL(new Blob([m.text],{type:'text/plain'}));const a=element('a');a.href=url;a.download='kod.'+extension;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function copyText(value){try{await navigator.clipboard.writeText(value);notify('Skopiowano.')}catch{notify('Nie udało się skopiować.')}}
function decorateMessage(row,m){extraMessages.set(m.id,m);const actions=element('div','message-actions');const copy=element('button','tiny-button','⧉ Kopiuj');copy.type='button';copy.title='Kopiuj tekst wiadomości';copy.onclick=()=>{if(m.kind==='text'||m.kind==='code')copyText(m.text);else notify('Ta wiadomość nie zawiera tekstu.')};const heart=element('button','tiny-button','♡');heart.type='button';heart.title='Dodaj serce';heart.onclick=()=>emitExtra({type:'reaction',id:m.id,emoji:'❤️'});const choose=element('button','tiny-button','＋');choose.type='button';choose.title='Wybierz reakcję';const reactionChoices=element('div','reaction-choices');reactionChoices.hidden=true;for(const emoji of EXTRA_EMOJI){const button=element('button','',emoji);button.type='button';button.setAttribute('aria-label','Zareaguj '+emoji);button.onclick=()=>{emitExtra({type:'reaction',id:m.id,emoji});reactionChoices.hidden=true};reactionChoices.append(button)}choose.onclick=()=>reactionChoices.hidden=!reactionChoices.hidden;const receipts=element('button','tiny-button read-status','👁 0');receipts.type='button';receipts.title='Nikt jeszcze nie odczytał';receipts.onclick=()=>notify(receipts.title);const reactions=element('div','reaction-list');actions.append(copy,heart,choose,reactionChoices,receipts,reactions);row.querySelector('.message-body').append(actions);paintExtraState(m.id);readObserver.observe(row);if(m.author.id!==selfId)setTimeout(()=>reportRead(m.id),100)}
function paintExtraState(id){const row=[...$('messages').querySelectorAll('.message-row')].find(e=>e.dataset.id===id);if(!row)return;const readers=[...(extraReads.get(id)||[])].filter(u=>u!==extraMessages.get(id)?.author.id);const read=row.querySelector('.read-status');if(read){read.textContent='👁 '+readers.length;read.title=readers.length?'Odczytali: '+readers.map(u=>people.get(u)?.nick||'Osoba, która wyszła').join(', '):'Nikt jeszcze nie odczytał'}const list=row.querySelector('.reaction-list');if(list){list.replaceChildren();for(const [emoji,users] of extraReactions.get(id)||[]){if(!users.size)continue;const b=element('button','reaction-pill'+(users.has(selfId)?' selected':''),emoji+' '+users.size);b.type='button';b.title=[...users].map(u=>people.get(u)?.nick||'Osoba, która wyszła').join(', ');b.onclick=()=>emitExtra({type:'reaction',id,emoji});list.append(b)}}}

async function sendAsset(file,sticker=false){if(!active){notify('Najpierw wejdź do pokoju.');return}if(!file||!file.size||file.size>EXTRA_MAX){notify('Plik może mieć maksymalnie 3 MB.');return}if(sticker&&!/^image\/(png|jpeg|webp|gif)$/.test(file.type)){notify('Naklejka musi być zdjęciem lub GIF-em.');return}const id=crypto.randomUUID();const name=file.name.slice(0,120)||'plik';const mime=file.type.slice(0,80)||'application/octet-stream';try{const bytes=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));const encoded=btoa(raw);const total=Math.ceil(encoded.length/EXTRA_CHUNK);const packet={type:'asset-chunk',owner:selfId,id,total,name,mime,size:file.size,sticker};for(let index=0;index<total;index++){const part={...packet,index,data:encoded.slice(index*EXTRA_CHUNK,(index+1)*EXTRA_CHUNK)};if(isHost){receiveExtraChunk(part,selfId);broadcast(part)}else if(!sendTo(hostConnection,part))throw Error('Połączenie zostało przerwane.');if(index%12===11)await new Promise(resolve=>setTimeout(resolve,10))}const message={type:'message',kind:'asset',asset:{id,name,mime,size:file.size,sticker}};if(isHost)publishMessage(selfId,message);else if(!sendTo(hostConnection,message))throw Error('Nie udało się wysłać pliku.');notify(sticker?'Naklejka wysłana.':'Plik wysłany.')}catch(e){notify(e.message||'Nie udało się wysłać pliku.')}}

$('attach-button').onclick=()=>$('attach-input').click();$('attach-input').onchange=()=>{const file=$('attach-input').files[0];if(file)sendAsset(file,false);$('attach-input').value=''};
for(const eventName of ['dragenter','dragover'])$('chat').addEventListener(eventName,event=>{if(!active||!event.dataTransfer?.types.includes('Files'))return;event.preventDefault();$('message-form').classList.add('drag-over')});
for(const eventName of ['dragleave','drop'])$('chat').addEventListener(eventName,event=>{if(!active)return;if(eventName==='drop'&&event.dataTransfer?.files.length){event.preventDefault();for(const file of [...event.dataTransfer.files].slice(0,5))sendAsset(file,false)}$('message-form').classList.remove('drag-over')});
$('code-button').onclick=()=>{$('code-dialog').showModal();$('code-input').focus()};$('cancel-code').onclick=()=>$('code-dialog').close();$('code-form').onsubmit=e=>{e.preventDefault();const text=$('code-input').value;if(!text.trim()){notify('Wklej kod przed wysłaniem.');return}if(text.length>20000){notify('Kod może mieć maksymalnie 20 000 znaków.');return}if(!active){notify('Najpierw wejdź do pokoju.');return}const data={type:'message',kind:'code',text,language:$('code-language').value};if(isHost)publishMessage(selfId,data);else if(!sendTo(hostConnection,data)){notify('Nie udało się wysłać kodu.');return}$('code-dialog').close();$('code-input').value=''};
$('code-input').onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();const input=e.target;input.setRangeText('  ',input.selectionStart,input.selectionEnd,'end')}};

function openStickerDatabase(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(Error());return}const request=indexedDB.open('pokoj-stickers',1);request.onupgradeneeded=()=>request.result.createObjectStore('stickers',{keyPath:'id'});request.onsuccess=()=>{stickerDatabase=request.result;resolve(stickerDatabase)};request.onerror=()=>reject(request.error)})}
async function loadSavedStickers(){try{const db=await openStickerDatabase();const records=await new Promise((resolve,reject)=>{const request=db.transaction('stickers').objectStore('stickers').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});savedStickers=records.slice(-20).map(record=>({...record,url:URL.createObjectURL(record.blob)}));if(pickerMode==='sticker'&&!$('picker').hidden)renderPicker()}catch{}}
const originalRenderPicker=renderPicker;
renderPicker=function(){originalRenderPicker();if(pickerMode!=='sticker')return;const button=element('button','add-sticker','＋ Dodaj własne zdjęcie / GIF');button.type='button';button.onclick=()=>stickerInput.click();$('picker-items').prepend(button);for(const sticker of savedStickers){const b=element('button','own-sticker');b.type='button';b.title=sticker.name;const img=element('img');img.src=sticker.url;img.alt=sticker.name;b.append(img);b.onclick=()=>{sendAsset(new File([sticker.blob],sticker.name,{type:sticker.blob.type}),true);setPicker(false)};$('picker-items').append(b)}};
const stickerInput=element('input');stickerInput.type='file';stickerInput.accept='image/png,image/jpeg,image/webp,image/gif';stickerInput.hidden=true;document.body.append(stickerInput);stickerInput.onchange=async()=>{const file=stickerInput.files[0];stickerInput.value='';if(!file)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type)||file.size>EXTRA_MAX){notify('Wybierz zdjęcie lub GIF do 3 MB.');return}try{if(savedStickers.length>=20)throw Error('Możesz zapisać maksymalnie 20 własnych naklejek.');const record={id:crypto.randomUUID(),name:file.name.slice(0,120),blob:file};const db=stickerDatabase||await openStickerDatabase();await new Promise((resolve,reject)=>{const request=db.transaction('stickers','readwrite').objectStore('stickers').put(record);request.onsuccess=resolve;request.onerror=()=>reject(request.error)});savedStickers.push({...record,url:URL.createObjectURL(file)});renderPicker();notify('Naklejka zapisana w tej przeglądarce.')}catch(e){notify(e.message||'Nie udało się zapisać naklejki.')}};
loadSavedStickers();

const originalResetSession=resetSession;
resetSession=function(){for(const asset of extraAssets.values())if(asset.url)URL.revokeObjectURL(asset.url);extraAssets.clear();extraMessages.clear();extraReads.clear();extraReactions.clear();originalResetSession()};
